server.port=9092

# Config db
spring.datasource.url=jdbc:postgresql://localhost:5432/db_logs_company
spring.datasource.username=postgres
spring.datasource.password=1998
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka Bootstrap server
spring.kafka.bootstrap-servers=localhost:9092

# Kafka order group
spring.kafka.consumer.group-id=order-group

# Kafka offset
spring.kafka.consumer.auto-offset-reset=latest

# Kafka Consumer
spring.kafka.consumer.send.log.topic=send_log_topic